FROM llm-service-kernel:fastapi-patched

ENV PYTHONPATH=/app \
    HF_HUB_OFFLINE=1 \
    TRANSFORMERS_OFFLINE=1

WORKDIR /app

COPY all-MiniLM-L6-v2 /models/all-MiniLM-L6-v2
COPY bge-base-en-v1.5 /models/bge-base-en-v1.5
COPY Qwen2.5-0.5B-Instruct /models/Qwen2.5-0.5B-Instruct

CMD ["/app/scripts/run_service.sh"]
