routing:
  servicePort: 8000

  epp:
    create: true
    service:
      type: ClusterIP
      port: 9002
      targetPort: 9002
      appProtocol: http2

  inferencePool:
    create: true
    name: ms-local-model-pool
    targetPortNumber: 8000
    modelServerType: vllm
    modelName: ${MODEL_NAME}
    modelServers:
      matchLabels:
        llm-d.ai/inference-serving: "true"

  inferenceModel:
    create: true

  httpRoute:
    create: false
