apiVersion: v1
data:
  APP_HOST: 0.0.0.0
  APP_PORT: "8080"
  AUTH_ENABLED: "0"
  BENCHMARK_SHADOW_MODE: "0"
  BGE_MODEL_PATH: /models/bge-base-en-v1.5
  CACHE_SCOPE: minikube-dev
  DEV_TENANT_ID: tenantA
  EXACT_CACHE_ENABLED: "0"
  HF_HUB_OFFLINE: "1"
  LLMD_API_MODE: chat
  LLMD_BASE_URL: http://infra-local-inference-gateway-istio.llm-d-local.svc.cluster.local:80
  LLMD_CHAT_PATH: /v1/chat/completions
  LLMD_COMPLETIONS_PATH: /v1/completions
  MILVUS_COLLECTION: rag_chunks_seaweed_v2
  MILVUS_URI: http://milvus.llm-service.svc.cluster.local:19530
  MODEL_BACKEND: llmd
  MODEL_SERVER_TIMEOUT_S: "300.0"
  RAG_BACKEND: milvus
  RAG_ENABLED: "1"
  RAG_MANIFEST_ROOT_DIR: /data/rag_store_tenants
  RAG_OBJECT_STORE_ACCESS_KEY_ID: llmbenchadmin
  RAG_OBJECT_STORE_BUCKET: llm-rag-store
  RAG_OBJECT_STORE_ENABLED: "1"
  RAG_OBJECT_STORE_ENDPOINT_URL: http://seaweed-s3.llm-service.svc.cluster.local:8333
  RAG_OBJECT_STORE_PREFIX: rag
  RAG_OBJECT_STORE_REGION: us-east-1
  RAG_OBJECT_STORE_SECRET_ACCESS_KEY: llmbenchsecretkey123
  RAG_OBJECT_STORE_USE_SSL: "false"
  RAG_OBJECT_STORE_VERIFY: "false"
  RAG_RETRIEVE_EVERY_REQUEST: "1"
  RETURN_DEBUG_BLOCKS: "1"
  SEM_CACHE_EMBED_MODEL_PATH: /models/all-MiniLM-L6-v2
  SEM_CACHE_ENABLED: "1"
  SEM_CACHE_MILVUS_URI: http://milvus.llm-service.svc.cluster.local:19530
  SEM_CACHE_MONGO_URI: mongodb://mongodb.llm-service.svc.cluster.local:27017
  SERVED_MODEL_NAME: qwen2.5-0.5b
  TENANT_CLAIM: tenant_id
  TOKENIZER_LOCAL_ONLY: "1"
  TOKENIZER_PATH: /models/Qwen2.5-0.5B-Instruct
  TRANSFORMERS_OFFLINE: "1"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"APP_HOST":"0.0.0.0","APP_PORT":"8080","AUTH_ENABLED":"0","BENCHMARK_SHADOW_MODE":"0","CACHE_SCOPE":"minikube-dev","DEV_TENANT_ID":"tenantA","EXACT_CACHE_ENABLED":"0","HF_HUB_OFFLINE":"1","LLMD_API_MODE":"completions","LLMD_BASE_URL":"http://infra-local-inference-gateway-istio.llm-d-local.svc.cluster.local:80","LLMD_CHAT_PATH":"/v1/chat/completions","LLMD_COMPLETIONS_PATH":"/v1/completions","MODEL_BACKEND":"llmd","MODEL_SERVER_TIMEOUT_S":"300.0","RAG_ENABLED":"0","RAG_RETRIEVE_EVERY_REQUEST":"0","RETURN_DEBUG_BLOCKS":"1","SEM_CACHE_ENABLED":"0","SERVED_MODEL_NAME":"qwen2.5-0.5b","TENANT_CLAIM":"tenant_id","TOKENIZER_LOCAL_ONLY":"1","TOKENIZER_PATH":"","TRANSFORMERS_OFFLINE":"1"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"llm-service-kernel-config","namespace":"llm-service"}}
  creationTimestamp: "2026-03-18T10:27:51Z"
  name: llm-service-kernel-config
  namespace: llm-service
  resourceVersion: "443133"
  uid: 7e5a27d3-fa2f-4492-861d-9ddee03d6494
